name: test

on: [ push ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: NPM config
        run: |
          npm config set //registry-lpm.listenai.com/:_password ${{ secrets.LPM_ZHUOBIN_TOKEN }}
          npm config set //registry-lpm.listenai.com/:username zbzhao
          npm config set //registry-lpm.listenai.com/:email zbzhao@listenai.com
          npm config set //registry-lpm.listenai.com/:always-auth true

      - name: Install dependencies
        run: npm install

      - name: Run prepack
        run: npm run prepack

      - name: Run pospack
        run: npm run prepack
